name: VersionUpdate

on: [push]

jobs:
  build:
    name: Update Version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update the version
      run: |
        git log -1 Frontend/stream.lua > .version
        ver=`git log -1 --pretty=format:"%H" Frontend/stream.lua`
        sed -i "1clocal version=\"$ver\"" Frontend/stream.lua

    - name: Commit changes
      uses: alexesprit/action-update-file@master
      with:
        file-path: |
          .version
          Frontend/stream.lua
        commit-msg: Update version
        github-token: ${{ secrets.GITHUB_TOKEN }}
